---
title: "01_DIABLO"
author: "Maria, zagor"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


library(mixOmics)
set.seed(123456) 


```



```{r}

fp = file.path('..', 'input')


fn = 'Enzymomics_only_24.txt'
E = read.delim(file = file.path(fp, fn), 
               header = TRUE, 
               sep = "\t", 
               quote = NULL,
               dec = ".", 
               fill = TRUE, 
               comment.char = '@')

fn = 'Metabolomics_only_24.txt'
M = read.delim(file = file.path(fp, fn), 
               header = TRUE, 
               sep = "\t", 
               quote = NULL,
               dec = ".", 
               fill = TRUE, 
               comment.char = '@')

fn = 'phosphoProteomics_filtered_sig_24.txt'
P = read.delim(file = file.path(fp, fn), 
               header = TRUE, 
               sep = "\t", 
               quote = NULL,
               dec = ".", 
               fill = TRUE, 
               comment.char = '@')

all(P$treatment == E$treatment)
all(P$treatment == M$treatment)


```


```{r}

data = list(Enz = as.matrix(E[, -1]),
            Met = as.matrix(M[, -1]),
            Pph = as.matrix(P[, -1]))



```

<https://mixomics.org/mixdiablo/diablo-tcga-case-study/>

```{r}


lapply(data, dim) # check their dimensions
Y = factor(E$treatment, levels = unique(E$treatment))
summary(Y)


```


```{r}


list.keepX = c(24, 24) # select arbitrary values of features to keep
list.keepY = c(24, 24)

# generate three pairwise PLS models
pls1 <- spls(data[["Enz"]], data[["Met"]], 
             keepX = list.keepX, keepY = list.keepY) 
pls2 <- spls(data[["Enz"]], data[["Pph"]], 
             keepX = list.keepX, keepY = list.keepY)
pls3 <- spls(data[["Met"]], data[["Pph"]], 
             keepX = list.keepX, keepY = list.keepY)

# plot features of first PLS
plotVar(pls1, cutoff = 0.5, title = "(a) enzymomics vs metabolomics", 
        legend = c("enzymomics", "metabolomics"), 
        var.names = FALSE, style = 'graphics', 
        pch = c(16, 17), cex = c(2,2), 
        col = c('darkorchid', 'lightgreen'))

# plot features of second PLS
plotVar(pls2, cutoff = 0.5, title = "(b) enzymomics vs phosphoproteomics", 
        legend = c("enzymomics", "phosphoproteomics"), 
        var.names = FALSE, style = 'graphics', 
        pch = c(16, 17), cex = c(2,2), 
        col = c('darkorchid', 'blue'))

# plot features of third PLS
plotVar(pls3, cutoff = 0.5, title = "(c) metabolomics vs phosphoproteomics", 
        legend = c("metabolomics", "phosphoproteomics"), 
        var.names = FALSE, style = 'graphics', 
        pch = c(16, 17), cex = c(2,2), 
        col = c('lightgreen', 'blue'))


```
```{r}

pls1 <- spls(data[["Enz"]], data[["Met"]], ncomp = 1, keepX = 24, keepY = 24)
pls2 <- spls(data[["Enz"]], data[["Pph"]], ncomp = 1, keepX = 24, keepY = 24)
pls3 <- spls(data[["Met"]], data[["Pph"]], ncomp = 1, keepX = 24, keepY = 24)


```
```{r}

cor(pls1$variates$X, pls1$variates$Y) # calculate correlation of miRNA and mRNA
cor(pls2$variates$X, pls2$variates$Y) # calculate correlation of miRNA and proteins
cor(pls3$variates$X, pls3$variates$Y) # calculate correlation of mRNA and proteins

```

```{r}

design = matrix(0.1, ncol = length(data), nrow = length(data), # for square matrix filled with 0.1s
                dimnames = list(names(data), names(data)))
diag(design) = 0 # set diagonal to 0s

design

```

```{r}

basic.diablo.model = block.splsda(X = data, Y = Y, ncomp = 5, design = design) # form basic DIABLO model

```
```{r}
## ---- fig.cap = "FIGURE 2: Choosing the number of components in `block.plsda` using `perf()` with 10 × 10-fold CV function in the `breast.TCGA` study. Classification error rates (overall and balanced, see Section 7.3) are represented on the y-axis with respect to the number of components on the x-axis for each prediction distance presented in PLS-DA"----

perf.diablo = perf(basic.diablo.model, validation = 'Mfold', folds = 10, nrepeat = 10) # run component number tuning with repeated CV

plot(perf.diablo) # plot output of tuning

```
```{r}
ncomp = perf.diablo$choice.ncomp$WeightedVote["Overall.BER", "centroids.dist"] # set the optimal ncomp value
perf.diablo$choice.ncomp$WeightedVote # show the optimal choice for ncomp for each dist metric
```

```{r}

 test.keepX = list (Met = c(5:9, seq(10, 18, 2), seq(20,30,5)),
                    Enz = c(5:9, seq(10, 18, 2), seq(20,30,5)),
                    Pph = c(5:9, seq(10, 18, 2), seq(20,30,5)))
 
 t1 = proc.time()
 tune.MIR = tune.block.splsda(X = data, Y = Y, ncomp = ncomp,
                               test.keepX = test.keepX, design = design,
                              validation = 'Mfold', folds = 10, nrepeat = 1,
                              cpus = 2, dist = "centroids.dist")
 t2 = proc.time()
 running_time = t2 - t1; running_time

list.keepX = tune.MIR$choice.keepX
list.keepX

save(tune.MIR,list.keepX, file = 'output/result-MIR-diablo_design0.1.RData')

```