---
title: "01_DE"
author: "Maria, MPE, zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 12
    fig_height: 9
    toc: yes
    toc_depth: 2
    toc_float: true
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(#dev = c('pdf', 'png'),  # this embeds pdf and crates scrolable blocks
                      dev = c('png', 'svg', 'pdf'), 
                      fig.align = 'center', 
                      fig.height = 9, 
                      fig.width = 12 ,
                      warning = FALSE, message = FALSE
                      )
# options(knitr.table.format = "html")

```




```{r, echo=FALSE}

rm(list = ls(all = TRUE))
gc()

set.seed(123456)


`%nin%` = Negate(`%in%`)

library(RColorBrewer)
library(raster)

# library(ComplexHeatmap)
# library(circlize)

library(ggplot2)

library(magrittr)



```



```{r}

fp = file.path('.')

fn = 'All_proteins_for_obtaining_GSEA.txt'



counts = data.table::fread(file = file.path(fp, fn))

fn = 'analytes.txt'
pheno = data.table::fread(file = file.path(fp, fn))
pheno = pheno[rowSums(pheno == '') == 0, ]

```





```{r}

group = factor(pheno$Group, levels = c( "control_24h",
                                        "myco_24",
                                        "infected_24h",
                                        "myco_infected_24h"
                                        ))
(n = length(levels(group)))

```



```{r}

palette = brewer.pal(n,"Paired")[c(1, 2, 3, 4)]

grid = raster(ncols=n, nrows = 1, xmn=1, xmx=n, ymn=1, ymx=2)

values(grid) = 1:n

par(mar=rep(0.5, 4))
plot(grid, 
     col=palette, 
     legend=FALSE, 
     axes = 0, 
     box=FALSE)
text(grid, labels = levels(group), srt = 90)

```



```{r}


rownames(counts) = counts$GeneID
reads.raw = edgeR::DGEList(counts=counts[, -1], group=group)


```






# Session

```{r}

# devtools::session_info()
sessionInfo()

```

