---
title: "04_filter_old-CKN"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 8
    toc: yes
    toc_depth: 2
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(#dev = c('pdf', 'png'),  # this embeds pdf and crates scrolable blocks
                      dev = c('png'), 
                      fig.align = 'center', 
                      fig.height = 8, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )
# options(knitr.table.format = "html")

```


```{r, echo=FALSE, warning=FALSE, message=FALSE}


# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("lionessR")

```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()

set.seed(123456)

```

# edges/pthways/connections

```{r}

fp = file.path('..', 'input')
fn = 'old_CKN_edges.txt'

edges = data.table::fread(file.path(fp, fn), header = TRUE)
edges = edges[, c(1:3)]
edges
edges = as.data.frame(edges)

```


```{r}

fp = file.path('..', 'output')
fn = '03_CKN_tomato-ath_prioritised.xlsx'

DE = openxlsx::read.xlsx(xlsxFile = file.path(fp, fn),
                         sheet = 1,
                         startRow = 1,
                         colNames = TRUE,
                         rowNames = FALSE,
                         detectDates = FALSE,
                         skipEmptyRows = TRUE,
                         skipEmptyCols = TRUE,
                         rows = NULL,
                         cols = NULL,
                         check.names = FALSE,
                         sep.names = ".",
                         namedRegion = NULL,
                         na.strings = "NA",
                         fillMergedCells = FALSE)
DE = DE[, -1]
rownames(DE) = DE$AthID
colnames(DE) = gsub('\\.txt', '', colnames(DE))
head(DE)

```


# find edges where both genes are DE

```{r}

colnames(DE)[1] = 'geneID2'
edgesX = merge(edges, DE, by = 'geneID2', all.x = FALSE, all.y = FALSE)
colnames(DE)[1] = 'geneID1'
edgesX = merge(edgesX, DE, by = 'geneID1', all.x = FALSE, all.y = FALSE)

# because we know how many contrasts we have, otherwise take care of indexes
colnames(edgesX[, 4:13])
colnames(edgesX[, 14:23])

# two-step filtering for simplification, if oyu want the fist network too
i = rowSums(edgesX[, 4:13], na.rm = TRUE)
j = rowSums(edgesX[, 14:23], na.rm = TRUE)
# remove ones with NA, i.e. no logFC on both sides
k = intersect(which(!is.na(i)), which(!is.na(j)))
edgesX = edgesX[k, ]
edgesX = edgesX[!duplicated(edgesX), ]


```

<!-- # find edges where both genes are DE in at least one conditions -->


```{r}

# i = rowSums(!is.na(edgesX[, 4:13]), na.rm = TRUE)
# j = rowSums(!is.na(edgesX[, 14:23]), na.rm = TRUE)
# hist(i)
# hist(j)
# k = intersect(which(i > 2), which(j > 2))
# 
# edgesY = edgesX[k, ]
# edgesY = edgesY[!duplicated(edgesY), ]
# 
# 
# # this means we have same Ath pair but different edge
# table(duplicated(edgesY[, 1:3]))
# table(duplicated(edgesY[, 1:2]))
# dup = edgesY[duplicated(edgesY[,1:2]), 1:2]
# ddup = edgesY[edgesY$geneID1 %in% dup$geneID1 & edgesY$geneID2 %in% dup$geneID2, 1:3]
# ddup = ddup[order(ddup$geneID2, ddup$geneID1), ]
# # bad to have this, but well...
# print(head(ddup))

```


```{r}
edgesY = edgesX
```


```{r}

fp = file.path('..', 'output', 'cytoscape')
dir.create(fp)
fn = 'for_cytscape-filtered.txt'

edgesY = edgesY[, 1:2]
edgesY = edgesY[!duplicated(edgesY), ]
edges = edges[!duplicated(edges), ]
edgesZ = merge(edgesY, edges, by = c('geneID1', 'geneID2'), all.x = TRUE, all.y = FALSE)

write.table(edgesZ, 
            file = file.path(fp, fn), 
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "NA", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = "escape",
            fileEncoding = "UTF-8")


```


# sessionInfo

```{r}

sessionInfo()

```

