---
title: "06_induced-subgraph"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 16
    fig_height: 9
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(#dev = c('pdf', 'png'),  # this embeds pdf and crates scrolable blocks
                      dev = c('png'), 
                      fig.align = 'center', 
                      fig.height = 9, 
                      fig.width = 16 ,
                      warning = FALSE, message = FALSE
                      )
# options(knitr.table.format = "html")

```


```{r,  echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()

set.seed(123456)


`%nin%` = Negate(`%in%`)

library(magrittr)


```



# full CKN (old)

```{r}

fp = file.path('..', 'input')
fs = 'old_CKN_edges.txt'



CKN = read.table(file.path(fp, fs),
                 header = TRUE, 
                 sep = "\t", 
                 quote = NULL,
                 dec = ".", 
                 stringsAsFactors = FALSE,
                 na.strings = "NA",
                 fill = TRUE,
                 comment.char = "#")
CKN = CKN[, 1:3]
colnames(CKN) = c('from', 'to', 'reaction')

```


# which genes/proteins you want

if only sig ones uncomment  ```IDs = pprot[pprot$significant, ]$ID``` and comment ```IDs = pprot$ID```

```{r}

fpt = file.path('..', '..', '_A_04_EnrichmentProteomics-R', 'output')
fs = 'phosphoProteomics-DE-DEP.txt'



prot = read.table(file.path(fpt, fs),
                 header = TRUE, 
                 sep = "\t", 
                 quote = NULL,
                 dec = ".", 
                 stringsAsFactors = FALSE,
                 na.strings = "NA",
                 fill = TRUE,
                 comment.char = "#")

# prot$ID = gsub('s', 'S',prot$ID)

pprot = prot[, grep('^ID$|^significant$', colnames(prot))]
table(pprot$significant)
IDs = pprot[pprot$significant, ]$ID
# IDs = pprot$ID
IDs = gsub('\\.1$', '', IDs)
print(IDs)

prot = prot[prot$significant, ]
prot = prot[, grep('^ID$|_ratio|_p\\.adj', colnames(prot))]
colnames(prot)[1] = 'SlyID'

```


```{r}

fn = 'tomato-arabidopsis-translation_dummy.txt'

translate = read.table(file.path(fp, fn),
                 header = TRUE, 
                 sep = "\t", 
                 quote = NULL,
                 dec = ".", 
                 stringsAsFactors = FALSE,
                 na.strings = "NA",
                 fill = TRUE,
                 comment.char = "#")

table(translate$SlyID %in% IDs)


prot$SlyID = gsub('\\.1$', '', prot$SlyID)

Ath = translate[translate$SlyID %in% IDs, ]$AthID


prot = merge(translate, prot, by = 'SlyID', all.x = FALSE, all.y = TRUE)


```


# igraph



```{r}

library(igraph)

```



<https://igraph.org/r/doc/read_graph.html>

## data frame to graph

<https://www.rdocumentation.org/packages/igraph/versions/0.5.5-4/topics/graph.data.frame>

```{r}

g = graph.data.frame(CKN, directed=TRUE, vertices=NULL)
print(g)

# nodes/vertices
V(g)
# edges/connections
E(g)
table(E(g)$reaction)

```

## induced subgraph

<https://igraph.org/r/doc/subgraph.html>

```{r}

ind = match(Ath, V(g)$name)
ind = ind[!is.na(ind)] # get rud if NA
gg = induced_subgraph(graph = g, vids = ind)

print(gg)
# plot(gg)


```


so this is useless

# Ego graph

 and we dont know why those two are not the same


```{r}



gg = make_ego_graph(
  g,
  order = 1,
  nodes = ind,
  mode = c("all"),
  mindist = 0
)


gg

for (i in ind) {
  print(neighbors(g, i))  
}


ggg = do.call(union, gg)
ggg




```



```{r}

fp = file.path('..', 'output', 'cytoscape')
fn = 'prot-DE_ego.txt'

df = as_edgelist(ggg)
colnames(df) = c('geneID1', 'geneID2')



write.table(df, 
            file = file.path(fp, fn), 
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "NA", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = "escape",
            fileEncoding = "UTF-8")






```




## shortest paths


<https://igraph.org/r/doc/distances.html>

```{r}

mylist = all_shortest_paths(g, from = ind, to = ind, mode = "all")
length(mylist$res)
table(Ath %in% unique(names(unlist(mylist$res))))
ind = unique(unlist(mylist$res))

gg = induced_subgraph(graph = g, vids = ind)

print(gg)
plot(gg, layout=layout_with_fr, vertex.size=4,
     vertex.label.dist=0.5, vertex.color="red", edge.arrow.size=0.5)

```

So this is better


## write output


<https://igraph.org/r/doc/as_edgelist.html>


```{r}

fp = file.path('..', 'output', 'cytoscape')
fn = 'prot-DE_shortest-paths.txt'

df = as_edgelist(gg)
df = as.data.frame(cbind(df, E(gg)$reaction))
colnames(df) = c('geneID1', 'geneID2', 'reactionType')

colnames(translate) = c('SlyID2', 'geneID2')
df = merge(df, translate, by = 'geneID2', all.x = TRUE, all.y = FALSE)
colnames(translate) = c('SlyID1', 'geneID1')
df = merge(df, translate, by = 'geneID1', all.x = TRUE, all.y = FALSE)

# remove untranslated
df = df[!is.na(df$SlyID2) & !is.na(df$SlyID1), ]


write.table(df, 
            file = file.path(fp, fn), 
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "NA", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = "escape",
            fileEncoding = "UTF-8")


fn = 'prot-DE_induced-subpaths_nodes.txt'

write.table(prot, 
            file = file.path(fp, fn), 
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "NA", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = "escape",
            fileEncoding = "UTF-8")


```






# sessionInfo

```{r}

sessionInfo()

```

